#!/usr/bin/env bash
# Paper-2 credibility run: one clean-fit map, the graded desync density ladder (pilot -> d3_max),
# and the multi-packer slice, all in a single invocation so ECE is comparable across the ladder.
# Emits the OOD baseline columns too. Serial, one binary in memory, resumable CSV.
#
# CANONICAL, REPRODUCIBLE SPLIT (the single source of truth for the paper's numbers):
#   seed 1; 20 clean-fit, 25 clean-holdout; 20 binaries per drift level (pilot, d1_med, d2_heavy,
#   d3_max) = 80 desync; 17 packed (NRV2 x8, LZMA x8, ls x1). Total 142 binaries.
#   n-per-level is capped at 20 because that is the largest uniform level the size-capped d3_max
#   corpus (22 binaries) can supply; --n-desync 20 makes every level deterministic from seed 1.
#   The committed credibility.csv is regenerated by THIS script; delete it first (the CSV is
#   resume-mode: an existing row is reused, not recomputed) so a rerun recomputes from HEAD.
set -euo pipefail
cd "$(dirname "$0")/../.."                      # upd-suite root
BIN=./target/release/consistency
CORP=~/lab/projects/probablistic/corpus         # clean + desync corpora live here
PK=docs/consistency_credibility/packed          # multi-packer corpus (built by make_upxgt.py)
OUT=docs/consistency_credibility

# multi-packer args: every carved specimen, labeled by UPX backend (nrv|lzma)
PACKED_ARGS=()
for f in "$PK"/*_upx_nrv;  do [ -e "$f" ] && PACKED_ARGS+=(--packed-spec nrv  "$f" "$f.upxgt"); done
for f in "$PK"/*_upx_lzma; do [ -e "$f" ] && PACKED_ARGS+=(--packed-spec lzma "$f" "$f.upxgt"); done

# Desync levels use SIZE-CAPPED corpora (stripped_small = binaries whose .text < ~180 KB). The Soft
# engine's factor graph is O(.text), and a single 700 KB d3_max binary spikes to many GB — enough to
# OOM the machine. Capping keeps peak RSS ~2 GB (pilot-sized) so the serial one-binary-at-a-time
# guarantee actually bounds memory. The gradient is unchanged: junk fraction is a per-build property,
# independent of binary size, so small binaries still span 3.4% -> 17.9% junk across the ladder.
"$BIN" \
  --clean-bins "$CORP/x86_64-binaries/elf/coreutils" --clean-gt "$CORP/gt" \
  --desync-bins "$CORP/desync-pilot/stripped" --desync-gt "$CORP/desync-gt" \
  --desync-level d1_med   "$CORP/desync-dense/d1_med/stripped_small"   "$CORP/desync-dense/d1_med/gt_small" \
  --desync-level d2_heavy "$CORP/desync-dense/d2_heavy/stripped_small" "$CORP/desync-dense/d2_heavy/gt_small" \
  --desync-level d3_max   "$CORP/desync-dense/d3_max/stripped_small"   "$CORP/desync-dense/d3_max/gt_small" \
  --packed "$(cd "$(dirname "$0")/../.." && pwd)/corpus_packed/ls_packed" \
  --packed-gt "$(cd "$(dirname "$0")/../.." && pwd)/corpus_packed/ls_packed.upxgt" \
  "${PACKED_ARGS[@]}" \
  --n-fit 20 --n-holdout 25 --n-desync 20 --seed 1 \
  --out "$OUT/credibility.csv" --summary "$OUT/credibility_summary.json"

# Record which engine actually produced the CSV. See docs/tools/engine_manifest.py -- probdisasm is
# a *path* dependency, so Cargo.lock pins only version 0.2.2 and nothing else on disk would say which
# checkout was built.
python3 docs/tools/engine_manifest.py stamp "$OUT"
